### PR TITLE
Add Lambert W function from `lambert_w`

### PR DESCRIPTION
**Pull request by JSorngard**
This PR adds the 50-bit versions of the Lambert W function from the [`lambert_w`](https://crates.io/crates/lambert_w) crate. 

I was unsure how testing was done in this crate, so I have not added any tests yet.

### CODE REVIEW

**Review by Axect — APPROVED** [review]
The implementation of lambert_w0 and lambert_wm1 looks clean and well-structured. Good job on integrating the 50-bit versions from the `lambert_w` crate.

**Comment by Axect** [comment]
Thank you for this contribution, @JSorngard.
Regarding testing, we've been using simple functionality checks in `src/bin` so far.
However, we're planning to introduce more rigorous tests soon. If you have any ideas or suggestions for comprehensive test cases, especially for these new functions, we'd greatly appreciate your input.

**Comment by Axect** [comment]
And I have a question regarding the implementation:

Given that Peroxide already successfully wraps the `lambert_w` crate (which you authored), I'm curious about the reasoning behind implementing the same functionality directly in Puruspe.
While we always welcome pure Rust implementations of special functions in Puruspe, I'd be interested to hear your thoughts on this potential duplication, especially considering the existing high-quality `lambert_w` crate.

Could you share your perspective on this? It would be helpful to understand the motivation behind this approach.

**Comment by JSorngard** [comment]
Ah, I probably misunderstood our conversation in the previous issue then, because I thought this duplication was what you proposed.  
It makes sense to just have the functionality in `lambert_w`. Should this PR be reverted?

**Comment by Axect** [comment]
I see, thanks for clarifying. I'll go ahead and revert this PR to avoid duplication.

Your contributions, including your work on the `lambert_w` crate, are truly valuable.
We greatly appreciate your involvement with Peroxide and your dedication to Rust scientific computing. Thank you again for your efforts.

**Comment by JSorngard** [comment]
I don't think I can comment too much on the change in philosophy, as I don't have the software engineering experience to understand in what situations a library with or without dependencies is preferred.

As for the implementation itself I think it makes a lot of sense. Then `peroxide` doesn't have to be aware of more than one special function library. I can get started on adding everything to `puruspe` today.

Would you prefer if I add the different accuracy versions as separate functions to `puruspe` and then have `peroxide` wrap it into a flexible implementation like now, or would you prefer if `puruspe` creates the flexible version of the function and `peroxide` just exposes it (and makes a simple wrapper in `prelude`)?  
I think I lean towards the first option, but I don't have a very strong opinion.

**Comment by Axect** [comment]
Thank you for sharing your thoughts and for your willingness to contribute. I really appreciate your input on the implementation.

Regarding your question, I agree with your inclination towards the first option. Importing the four key functions from `lambert_w` directly into `puruspe` and then creating the wrapper in `peroxide` seems like the best approach. This way, we only need to modify the dependency part in `peroxide`, and `puruspe` users can use the functions as cleanly as you intended in `lambert_w`.

To move forward with this, I propose the following concrete steps:

1. I'll create a new `v0.3.0` branch in the `puruspe` repository.
2. I'll also create a corresponding issue for tracking the v0.3.0 development. This issue will outline our goals, including integrating the `lambert_w` dependency and implementing comprehensive tests.
3. We can use this branch and issue to collaboratively work on the implementation, track our progress, and discuss any challenges that arise.

Working in this dedicated branch will allow us to thoroughly develop and test the changes before merging them into the main branch. Once we're satisfied with the implementation and testing, we can publish v0.3.0, which will be a significant improvement to `puruspe`.

What do you think about this approach? If you're on board, I can set up the branch and issue right away, and we can start the implementation process. Please let me know if you have any questions or suggestions before we begin.

**Comment by JSorngard** [comment]
I think that outline sounds good! 👍

**Comment by Axect** [comment]
I've created the v0.3.0 branch and opened an issue to track our progress:

Issue: Develop puruspe v0.3.0: Integrate lambert_w and Implement Comprehensive Tests #12

The branch is now ready for development. Feel free to start working on the integration of `lambert_w` functions into `puruspe`. If you have any questions or need any assistance, please don't hesitate to ask in the issue thread. Let's collaborate to make this a great release!

**Pull request merged**
