### PR TITLE
Add script for generating test data, and a test of `lambert_w0`, `sp_lambert_w0`, `lambert_wm1`, `sp_lambert_wm1`

### PR DESCRIPTION
**Pull request by JSorngard**
This is my proposal for a test of the Lambert W functions.

### CODE REVIEW

**Comment by Axect** [comment]
The code appears to be perfect. However, as it's currently midnight in Korea, I've already left the lab for the day. I'll thoroughly review and incorporate your changes after I return to work tomorrow morning. I kindly ask for your understanding in this matter.

**Comment by JSorngard** [comment]
Of course. I will work on moving the functions and their tests into their own file in the meantime.

**Review by Axect — APPROVED** [review]

**Comment by Axect** [comment]
Thank you for your excellent contribution, @JSorngard! Your work on implementing tests for the Lambert W functions is truly impressive. I'd like to share some thoughts on your changes and propose a few adjustments. I'd greatly appreciate your input on these ideas:

1. Test Implementation: Your tests are exemplary. They thoroughly validate the accuracy of the Lambert W functions, which is crucial for our library. Great job on this!

2. Module Structure: While I appreciate the effort to organize the code, I'm concerned that the current structure with `local_lambert_w.rs` might become complex if we add more external dependencies. Instead, I propose simplifying `lib.rs` to just:

   ```rust
   pub use lambert_w;
   ```

   This approach is clean and allows for intuitive usage:
   
   ```rust
   use puruspe::gamma::ln_gamma;
   use puruspe::lambert_w::lambert_w0;
   ```

   The crate name 'lambert_w' is already intuitive, so we don't need to use an alias.

3. Test Location: I suggest moving the tests to a separate file, `tests/lambert_w_test.rs`. This would keep our test code organized while maintaining a simple main library structure.

4. Prelude: We could create a prelude for users who want to import all functions at once. What do you think about this idea?

If you're comfortable with these suggestions, I'd like to proceed with the following changes:

1. Simplify the module structure by removing `local_lambert_w.rs` and updating `lib.rs` as shown above.
2. Move the tests to a new `tests/lambert_w_test.rs` file.
3. Create a prelude for convenient imports.

I value your input and would be happy to discuss any concerns or alternative ideas you might have. If these changes sound good to you, I'm prepared to start working on them directly in the repository.

Once again, thank you for your valuable contribution and the impressive accuracy of the Lambert W functions. Your work significantly enhances the quality of our library.

**Comment by JSorngard** [comment]
I think the file restructure and module renaming is a very good idea. It would make it clearer, and simpler.

Moving the tests make sense I think.

Regarding the prelude, would it not work for the user to do `use puruspe::*;` to import everything? I interpreted the different function specific modules to not be exposed to the user, but that everything is organized like now from a user perspective.

**Comment by Axect** [comment]
Thank you for your feedback. I really appreciate your insights.

- I'm glad you agree with the file restructure and module renaming ideas. Your support for these changes is valuable. I'll proceed with merging the current PR and then immediately start working on these modifications.

- You're absolutely right about the current functionality of `use puruspe::*;`. It's already working as intended and is indeed a reasonable approach. After considering your point, I agree that adding a separate prelude would be unnecessary.

- Your suggestion to keep the direct exports in `lib.rs` to allow users to simply use `use puruspe::*;` is spot on. It maintains simplicity while providing easy access to all functions. We'll stick with this approach rather than introducing a new prelude.

Thank you again for your contributions and thoughtful feedback. It's helping us make puruspe more intuitive and user-friendly. I'll start implementing these changes right after merging the current PR.

**Pull request merged**
